version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:16.17.0-browsers
    steps:
      - checkout
      - run: echo "Running tests"
      - run: npm ci
      - run: npm test

workflows:
  test_build:
    jobs:
      - test