version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:16.17
    steps:
      - checkout
      - run: echo "Running tests"
      - run: npm ci
      - run: npm test

workflows:
  test_build:
    jobs:
      - test